### ISSUE TITLE
does not work if category is afterwards choosen

### ISSUE THREAD

**Issue by Jey-Cee** [julianlam/nodebb-plugin-canned-responses#18]
If you open up a new topic from any other category and change the category in composer afterwards the template will not be inserted.

Is this known, bug or feature?

**Comment by julianlam** [comment]
Hi @Jey-Cee are you referring to the default canned response when creating a new topic? I don't think this plugin supports that at the moment...

**Comment by julianlam** [comment]
673bee3

**Comment by julianlam** [comment]
v2.3.0 contains this fix. If you have text already typed, it will throw a toaster warning to ask if you want to append.

**Comment by Jey-Cee** [comment]
Nice, Thank you julian.
