### ISSUE TITLE
1.0.3 compatibility

### ISSUE THREAD

**Issue by wayneworkman** [julianlam/nodebb-plugin-canned-responses#2]
Hello from forums.fogproject.org again,

This request is in relation to this issue:
https://github.com/NodeBB/NodeBB/issues/4692

Can this be updated to work with NodeBB 1.0.3 ?

Thanks,
Wayne

**Comment by julianlam** [comment]
If the plugin does not show up on the plugins page, it probably just needs its compatibility info updated.

It is working with the latest version of NodeBB: `npm i nodebb-plugin-canned-responses`

**Comment by julianlam** [comment]
v1.0.5
