### ISSUE TITLE
site-wide canned-response for opening-post of a thread

### ISSUE THREAD

**Issue by wayneworkman** [julianlam/nodebb-plugin-canned-responses#3]
Hello,

Is there a way to create a site-wide template using the canned responses plugin? At forums.fogproject.org we would like all opening-posts of new threads to have a canned response that users can edit, so that we do not have to ask repetitive questions over and over.

Currently, canned responses with this plugin are per-user and must be setup by individual users. We would like to force a canned response site-wide but only for opening thread posts.

Thanks,
Wayne

**Comment by julianlam** [comment]
Hi Wayne!

That's a neat idea... but I'm assuming you wouldn't want it forum-wide, as there are some forums where you'd just be discussing project related things, no?

**Comment by wayneworkman** [comment]
If it's simple to set it per-topic, that'd be great. If it's not simple to do, don't worry about all that and please focus on a site-wide canned-response for every user. 

We really, really need it.

**Comment by wayneworkman** [comment]
I just wanted to touch base here.
On nodebb's main github project, when you create an "issue", it has forced canned responses.

That's what we want for forums.fogproject.org with nodebb and the canned response plugin.

**Comment by julianlam** [comment]
In progress...
