### ISSUE TITLE
Deleting a template causes the entire forum to crash

### ISSUE THREAD

**Issue by deiden26** [julianlam/nodebb-plugin-canned-responses#8]
After deleting a template, this error is thrown whenever one goes into the admin panel
```
TypeError: Cannot read property 'text' of null
NodeBB/node_modules/nodebb-plugin-canned-responses/lib/responses.js:28:52
```

The following error is thrown when someone attempts to visit the forum itself
```
TypeError: Cannot set property 'id' of null
NodeBB/node_modules/nodebb-plugin-canned-responses/lib/responses.js:43:17
```

**Comment by deiden26** [comment]
I have identified the issue.

```
responses.delete = function(responseId, uid, callback) {
	async.parallel([
		async.apply(db.delete, 'canned-responses:' + responseId),
		async.apply(db.sortedSetRemove, 'canned-responses:index:' + uid, responseId)
	], callback);
};
```

The admin's uid is used when deleting a site-wide responses, but these responses are stored in the set `canned-responses:index:0`. The admin's uid will never be 0

**Comment by julianlam** [comment]
Thanks @deiden26 ! Back in-office now, so happy to resolve this one for you.

**Comment by julianlam** [comment]
v2.0.1
